apiVersion: apps/v1
kind: Deployment
metadata:
  name: thales-directory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: thales-directory
          image: thales-directory:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
