"""add skills, current_project, languages_spoken to user

Revision ID: 105f45b42815
Revises: bbac445d8e0b
Create Date: 2025-07-23 14:55:01.900034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105f45b42815'
down_revision: Union[str, Sequence[str], None] = 'bbac445d8e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('current_project', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('languages_spoken', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'languages_spoken')
    op.drop_column('users', 'current_project')
    op.drop_column('users', 'skills')
    # ### end Alembic commands ###
