"""rename departement to department

Revision ID: 1e54e19ab5ed
Revises: edf0fb3a635c
Create Date: 2025-07-20 12:59:26.905611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e54e19ab5ed'
down_revision: Union[str, Sequence[str], None] = 'edf0fb3a635c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    pass 

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('poste', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('departement', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'department')
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
