"""Add hire_date to user

Revision ID: bbac445d8e0b
Revises: 1e54e19ab5ed
Create Date: 2025-07-22 11:51:55.270306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbac445d8e0b'
down_revision: Union[str, Sequence[str], None] = '1e54e19ab5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hire_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hire_date')
    # ### end Alembic commands ###
